-- ATIVIDADE 1
create DATABASE db_generation_game_online;
USE db_generation_game_online;
 create TABLE tb_classes(
 id BIGINT AUTO_INCREMENT,
 EQUIPE VARCHAR(200),
 MISSAO VARCHAR (400),
 PRIMARY KEY (id)
 );
 INSERT INTO tb_classes (EQUIPE,MISSAO)
 VALUE("ESMERALDA","SUA MISSÃO É ROUBAR A COROA DE DIAMANTE DA RAINHA E MATAR O REI");
INSERT INTO tb_classes (EQUIPE,MISSAO)
 VALUE("RUBI","SUA MISSÃO É MATAR TODOS JOGADORES VAMPIROS E ROUBAR O CALICE DOS VAMPIROS");
INSERT INTO tb_classes (EQUIPE,MISSAO)
 VALUE("AMETISTA","SUA MISSÃO É PROTEGER A FAMILIA REAL E MATAR TODOS OS JOGADORES LOBSOMENS");
INSERT INTO tb_classes (EQUIPE,MISSAO)
 VALUE("SAFIRA","SUA MISSÃO É MATAR OS CAÇADORES E CRIAR UMA ALINÇA COM A EQUIPE RUBI");
INSERT INTO tb_classes (EQUIPE,MISSAO)
 VALUE(" JADE","SUA MISSÃO É PROTEGER OS LOBSOMENS E CAÇADORES E MATAR O PRINCIPE");
 
 create TABLE tb_personagens(
 ID BIGINT auto_increment,
 NOME VARCHAR (200),
 IDADE INT,
 CRIATURA_MISTICA VARCHAR(100),
 PODER VARCHAR(100),
 ATAQUE INT,
 DEFESA INT,
 PRIMARY KEY (ID),
 CLASSES_ID BIGINT,
 FOREIGN KEY (CLASSES_ID) REFERENCES tb_classes(id)
 );
 INSERT INTO tb_personagens (NOME,IDADE,CRIATURA_MISTICA,ATAQUE,DEFESA,CLASSES_ID)
 VALUE("SAMANTHA JONES",800,"VAMPIRA",5000,1000,3);
 INSERT INTO tb_personagens (NOME,IDADE,CRIATURA_MISTICA,ATAQUE,DEFESA,CLASSES_ID)
 VALUE("LOGAN BROWN",24,"LOBSOMEN",2100,4700,4);
 INSERT INTO tb_personagens (NOME,IDADE,CRIATURA_MISTICA,ATAQUE,DEFESA,CLASSES_ID)
 VALUE("FLORA EVANS",200,"FADA",1999,5500,3);
 INSERT INTO tb_personagens (NOME,IDADE,CRIATURA_MISTICA,ATAQUE,DEFESA,CLASSES_ID)
 VALUE("MARCOS WILLIAMS",32,"CAÇADOR",5900,1300,1);
 INSERT INTO tb_personagens (NOME,IDADE,CRIATURA_MISTICA,ATAQUE,DEFESA,CLASSES_ID)
 VALUE("TYLER SMITH",1200,"VAMPIR0",6000,2000,5);
 INSERT INTO tb_personagens (NOME,IDADE,CRIATURA_MISTICA,ATAQUE,DEFESA,CLASSES_ID)
 VALUE("ALISSON DAVIES",21,"CAÇADORA",3000,2400,2);
 INSERT INTO tb_personagens (NOME,IDADE,CRIATURA_MISTICA,ATAQUE,DEFESA,CLASSES_ID)
 VALUE("AMELIA COOPER",104,"RAINHA E FADA",1980,4000,2);
 INSERT INTO tb_personagens (NOME,IDADE,CRIATURA_MISTICA,ATAQUE,DEFESA,CLASSES_ID)
 VALUE("DEREK COPPER",550,"REI E LOBSOMEN",4000,4100,3);
 
 ALTER TABLE tb_personagens drop column PODER;
 SELECT * FROM tb_personagens WHERE ATAQUE>2000;
 SELECT * FROM tb_personagens WHERE ATAQUE>=1000 AND ATAQUE<2001; 
 SELECT * FROM tb_personagens WHERE NOME LIKE' %C%';
 SELECT * FROM tb_personagens INNER JOIN tb_classes ON tb_classes.id = tb_personagens.CLASSES_ID;



-- ATIVIDADE 2
create DATABASE db_pizzaria_legal;
USE db_pizzaria_legal;
create TABLE tb_categoria(
id BIGINT AUTO_INCREMENT,
BORDA VARCHAR(50),
PRECO decimal(3.2),
PRIMARY KEY (id)
);
INSERT INTO tb_categoria (BORDA,PRECO)
VALUE("catupiry",20.50);
INSERT INTO tb_categoria (BORDA,PRECO)
VALUE("CHEDDAR",22.00);
INSERT INTO tb_categoria (BORDA,PRECO)
VALUE("CHOCOLATE",25.00);
INSERT INTO tb_categoria (BORDA,PRECO)
VALUE("QUEIJO",27.00);
INSERT INTO tb_categoria (BORDA,PRECO)
VALUE("GOIABADA",21.00);

create TABLE tb_pizzas(
id BIGINT AUTO_INCREMENT,
SABOR VARCHAR(50),
INGREDIENTES VARCHAR(255),
PRECO DECIMAL,
REFRIGERANTE BOOLEAN,
primary key (ID),
CATEGORIA_ID BIGINT,
FOREIGN KEY (CATEGORIA_ID) REFERENCES tb_categoria(id)
);
INSERT INTO tb_pizzas (SABOR,INGREDIENTES,PRECO,REFRIGERANTE,CATEGORIA_ID)
VALUES("FRANGO CATUPIRY","FRANGO, CATUPIRY E MILHO",40.00,TRUE,1);
INSERT INTO tb_pizzas (SABOR,INGREDIENTES,PRECO,REFRIGERANTE,CATEGORIA_ID)
VALUES("CALABRESA","CALABRESA COM CEBOLA OU QUEIJO",42.00,TRUE,4);
INSERT INTO tb_pizzas (SABOR,INGREDIENTES,PRECO,REFRIGERANTE,CATEGORIA_ID)
VALUES("PORTUGUESA","PRSUNTO,QUEIJO,TOMATE,AZEITONA,OVO,CEBOLA",45.00,TRUE,4);
INSERT INTO tb_pizzas (SABOR,INGREDIENTES,PRECO,REFRIGERANTE,CATEGORIA_ID)
VALUES("BROCOLIS","BROCOLIS, QUEIJO, CATUPIRY, TOMATE, AZEITONA",40.00,TRUE,1);
INSERT INTO tb_pizzas (SABOR,INGREDIENTES,PRECO,REFRIGERANTE,CATEGORIA_ID)
VALUES("CHOCOLATE","CHOCOLATE, MORANGO E LEITE CONDENSADO",50.00,TRUE,3);
INSERT INTO tb_pizzas (SABOR,INGREDIENTES,PRECO,REFRIGERANTE,CATEGORIA_ID)
VALUES("ROMEU E JULIETA","GOIABADA, LEITE CONDENSADO OU CHOCOLATE",50.00,TRUE,5);
INSERT INTO tb_pizzas (SABOR,INGREDIENTES,PRECO,REFRIGERANTE,CATEGORIA_ID)
VALUES("VEGETARIANA","BROCOLIS, MILHO, TOMATE, QUEIJO,CATUPIRY,PALMITO",47.00,TRUE,1);
INSERT INTO tb_pizzas (SABOR,INGREDIENTES,PRECO,REFRIGERANTE,CATEGORIA_ID)
VALUES("MEXICANA","CARNE SECA,CEBOLA, REQUEIJÃO,QUEIJO",50.00,TRUE,2);

SELECT * FROM tb_pizzas WHERE PRECO>45.00;
SELECT * FROM tb_pizzas WHERE PRECO>50.00 AND PRECO<100.00;
SELECT * FROM tb_pizzas WHERE SABOR LIKE '%M%';
SELECT * FROM tb_pizzas INNER JOIN tb_categoria ON tb_categoria.id=tb_pizzas.CATEGORIA_ID;
SELECT * FROM tb_pizzas INNER JOIN tb_categoria ON tb_categoria.id=tb_pizzas.CATEGORIA_ID 
WHERE tb_pizzas.CATEGORIA_ID=5 AND 3;


-- ATIVIDADE 3
create DATABASE db_farmacia_bem_estar;
USE db_farmacia_bem_estar;
create TABLE tb_categorias(
id BIGINT AUTO_INCREMENT,
REMEDIO_PARA VARCHAR(100),
RECEITA BOOLEAN,
PRIMARY KEY (id)
);
INSERT INTO tb_categorias(REMEDIO_PARA, RECEITA)
VALUE("DOR",FALSE);
INSERT INTO tb_categorias(REMEDIO_PARA, RECEITA)
VALUE("ANSIEDADE",TRUE);
INSERT INTO tb_categorias(REMEDIO_PARA, RECEITA)
VALUE("GRIPE",FALSE);
INSERT INTO tb_categorias(REMEDIO_PARA, RECEITA)
VALUE("ALERGIa",FALSE);
INSERT INTO tb_categorias(REMEDIO_PARA, RECEITA)
VALUE("INFECÇÃO",TRUE);
INSERT INTO tb_categorias(REMEDIO_PARA, RECEITA)
VALUE("OUTROS",TRUE);

create TABLE tb_produtos(
id BIGINT AUTO_INCREMENT,
NOME VARCHAR(50),
PRECO DECIMAL,
PESO_QUANTIDADE VARCHAR(100),
primary key (id),
CATEGORIAS_ID BIGINT,
FOREIGN KEY (CATEGORIAS_ID) REFERENCES tb_categorias(id)
);
INSERT INTO tb_produtos(NOME,PRECO,PESO_QUANTIDADE,CATEGORIAS_ID)
VALUE("DIPIRONA",10.00,"300 ML",1);
INSERT INTO tb_produtos(NOME,PRECO,PESO_QUANTIDADE,CATEGORIAS_ID)
VALUE("ALEGRA",50.00,"20 COMPRIMIDOS",4);
INSERT INTO tb_produtos(NOME,PRECO,PESO_QUANTIDADE,CATEGORIAS_ID)
VALUE("PASSIFLORA",65.00,"30 COMPRIMIDOS",2);
INSERT INTO tb_produtos(NOME,PRECO,PESO_QUANTIDADE,CATEGORIAS_ID)
VALUE("ANTIBIOTICO",78.00,"20 COMPRIMIDOS",5);
INSERT INTO tb_produtos(NOME,PRECO,PESO_QUANTIDADE,CATEGORIAS_ID)
VALUE("RIVOTRIL",100.00,"300 ML",2);
INSERT INTO tb_produtos(NOME,PRECO,PESO_QUANTIDADE,CATEGORIAS_ID)
VALUE("CINEGRIPE",35.00,"25 COMPRIMIDOS",3);
INSERT INTO tb_produtos(NOME,PRECO,PESO_QUANTIDADE,CATEGORIAS_ID)
VALUE("BUSCOPAN",39.00,"20 COMPRIMIDOS",1);
INSERT INTO tb_produtos(NOME,PRECO,PESO_QUANTIDADE,CATEGORIAS_ID)
VALUE("LORATADINA",25.00,"30 COMPRIMIDOSW",4);

SELECT * FROM tb_produtos WHERE PRECO>50;
SELECT * FROM tb_produtos WHERE PRECO>5 AND PRECO <61;
SELECT * FROM tb_produtos WHERE NOME LIKE '%C%';
SELECT * FROM tb_produtos INNER JOIN tb_categorias ON tb_categorias.id= tb_produtos.CATEGORIAS_ID;
SELECT * FROM tb_produtos INNER JOIN tb_categorias ON tb_categorias.id= tb_produtos.CATEGORIAS_ID
WHERE tb_categorias.REMEDIO_PARA="DOR";




-- ATIVIDADE 4
create database db_cidade_das_carnes;
use db_cidade_das_carnes;

create table tb_categoria(
id bigint auto_increment,
descricao varchar(255) ,
ativo boolean,
primary key (id)
);

insert tb_categoria (descricao, ativo) values ("Bovino",true);
insert tb_categoria (descricao, ativo) values ("Suino",true);
insert tb_categoria (descricao, ativo) values ("Aves",true);
insert tb_categoria (descricao, ativo) values ("pertence feijoada",true);
insert tb_categoria (descricao, ativo) values ("imbutidos",true);
insert tb_categoria (descricao, ativo) values ("outros",true);

create table tb_produtos (
id bigint(5) auto_increment,
nome varchar (255) ,
preco decimal,
qtProduto int ,
categoria_id bigint,
primary key (id),
FOREIGN KEY (categoria_id) REFERENCES tb_categoria (id)
);

insert tb_produtos (nome, preco, qtProduto, categoria_id)
 values ("ASA",40.00,30,3);
insert tb_produtos (nome, preco, qtProduto, categoria_id) 
values ("Picanha",70.00,30,1);
insert tb_produtos (nome, preco, qtProduto, categoria_id) 
values ("coxa de frango",50.00,30,3);
insert tb_produtos (nome, preco, qtProduto, categoria_id) 
values ("Bacon",30.00,30,1);
insert tb_produtos (nome, preco, qtProduto, categoria_id) 
values ("hamburguer",60.00,30,5);
insert tb_produtos (nome, preco, qtProduto, categoria_id) 
values ("Cupim",20.00,30,1);
insert tb_produtos (nome, preco, qtProduto, categoria_id) 
values ("Peito de frango",25.00,30,3);
insert tb_produtos (nome, preco, qtProduto, categoria_id) 
values ("Salame",18.00,30,5);


select * from tb_produtos where preco>50.00;
select * from tb_produtos where preco>50.00 and preco<150.00;
select * from tb_produtos where nome like '%c%';
select * from tb_produtos inner join tb_categoria on  tb_categoria.id = tb_produtos.categoria_id;
select * from tb_produtos inner join tb_categoria on  tb_categoria.id = tb_produtos.categoria_id 
where descricao="Bovino";



-- ATIVIDADE 5
create DATABASE db_construindo_vidas;
USE db_construindo_vidas;
create TABLE tb_categoria(
id BIGINT auto_increment,
COMODO VARCHAR (50),
SERVICO BOOLEAN,
PRIMARY KEY (id)
);
insert into tb_categoria(COMODO,SERVICO)
VALUE("BANHEIRO",TRUE);
insert into tb_categoria(COMODO,SERVICO)
VALUE("BANHEIRO",FALSE);
insert into tb_categoria(COMODO,SERVICO)
VALUE("PISO INDEPENDENTE DO COMODODO",TRUE);
insert into tb_categoria(COMODO,SERVICO)
VALUE("COZINHA",TRUE);
insert into tb_categoria(COMODO,SERVICO)
VALUE("COZINHA",FALSE);
insert into tb_categoria(COMODO,SERVICO)
VALUE("QUARTO",TRUE);
insert into tb_categoria(COMODO,SERVICO)
VALUE("QUARTO",FALSE);
insert into tb_categoria(COMODO,SERVICO)
VALUE("OUTRO",TRUE);
insert into tb_categoria(COMODO,SERVICO)
VALUE("OUTRO",FALSE);

create TABLE tb_produtos(
id BIGINT AUTO_INCREMENT,
NOME VARCHAR(100),
PRECO DECIMAL,
COR VARCHAR (110),
QUANTIDADE INT,
PRIMARY KEY (id),
CATEGORIA_ID BIGINT,
FOREIGN KEY (CATEGORIA_ID) REFERENCES tb_categoria (id)
);
INSERT INTO  tb_produtos (NOME,PRECO,COR,QUANTIDADE,CATEGORIA_ID)
VALUE("PRIVADA",180.00,"BRANCA OU PRETA",100,1);
INSERT INTO  tb_produtos (NOME,PRECO,COR,QUANTIDADE,CATEGORIA_ID)
VALUE("PIA",169.00,"BRANCA, PRETA OU AZUL",203,1);
INSERT INTO  tb_produtos (NOME,PRECO,COR,QUANTIDADE,CATEGORIA_ID)
VALUE("PISO",700.00,"PRETO, AZUL, ROSA",10000,3);
INSERT INTO  tb_produtos (NOME,PRECO,COR,QUANTIDADE,CATEGORIA_ID)
VALUE("CIMENTO",150.00,"MARCA CAMALEÃO",1500,9);
INSERT INTO  tb_produtos (NOME,PRECO,COR,QUANTIDADE,CATEGORIA_ID)
VALUE("TOMADA",50.00,"BRANCA,PRETA, ROXA OU ROSA",10900,8);
INSERT INTO  tb_produtos (NOME,PRECO,COR,QUANTIDADE,CATEGORIA_ID)
VALUE("GESSO",160.00,"BRANCO/ MARCA: CAMALEÃO",1110,8);
INSERT INTO  tb_produtos (NOME,PRECO,COR,QUANTIDADE,CATEGORIA_ID)
VALUE("CHUVEIRO COM BLUETOOTH",500.00,"BRANCO,PRETO OU PRATA",180,1);
INSERT INTO  tb_produtos (NOME,PRECO,COR,QUANTIDADE,CATEGORIA_ID)
VALUE("JANELA",190.00,"BRANCA, PRETA, DOURADA OU PRATA",199,6);

SELECT * FROM tb_produtos WHERE preco>100.00;
SELECT * FROM tb_produtos WHERE preco>70.00 and preco<151.00;
SELECT * FROM tb_produtos WHERE NOME LIKE '%C%';
select * from tb_produtos inner join tb_categoria on  tb_categoria.id = tb_produtos.CATEGORIA_ID;
select * from tb_produtos inner join tb_categoria on  tb_categoria.id = tb_produtos.CATEGORIA_ID
WHERE COMODO="BANHEIRO";




-- ATIVIDADE 6
create DATABASE db_curso_da_minha_vida;
USE db_curso_da_minha_vida;
create table tb_categorias(
id BIGINT AUTO_INCREMENT,
PERIODO VARCHAR (50),
TIPO VARCHAR (100),
PRIMARY KEY (id)
);
INSERT INTO tb_categorias(PERIODO,TIPO)
VALUE("MANHÃ","PRESENCIAL");
INSERT INTO tb_categorias(PERIODO,TIPO)
VALUE("MANHÃ","REMOTO/EAD");
INSERT INTO tb_categorias(PERIODO,TIPO)
VALUE("TARDE","PRESENCIAL");
INSERT INTO tb_categorias(PERIODO,TIPO)
VALUE("TARDE","REMOTO/EAD");
INSERT INTO tb_categorias(PERIODO,TIPO)
VALUE("NOITE","PRESENCIAL");
INSERT INTO tb_categorias(PERIODO,TIPO)
VALUE("NOITE","REMOTO/EAD");

create TABLE tb_cursos(
id BIGINT AUTO_INCREMENT,
NOME_CURSO VARCHAR(100),
TEMPO_CURSO INT,
PRECO DECIMAL,
PROFESSOR VARCHAR(100),
PRIMARY KEY(id),
CATEGORIAS_ID BIGINT,
FOREIGN KEY (CATEGORIAS_ID) REFERENCES tb_categorias (id)
);
INSERT INTO tb_cursos (NOME_CURSO,TEMPO_CURSO,PRECO,PROFESSOR,CATEGORIAS_ID)
VALUE("ADMINISTRAÇÃO",4,5500.00,"FABIO GONZALES",1);
INSERT INTO tb_cursos (NOME_CURSO,TEMPO_CURSO,PRECO,PROFESSOR,CATEGORIAS_ID)
VALUE("ADMINISTRAÇÃO",3,3500.00,"MARIA APARECIDA SOUZA",2);
INSERT INTO tb_cursos (NOME_CURSO,TEMPO_CURSO,PRECO,PROFESSOR,CATEGORIAS_ID)
VALUE("LOGISTICA",5,5800.00,"GEOVANNA RIBEIRO",5);
INSERT INTO tb_cursos (NOME_CURSO,TEMPO_CURSO,PRECO,PROFESSOR,CATEGORIAS_ID)
VALUE("LOGISTICA",4,2800.00,"ROBERTO SOUZA",4);
INSERT INTO tb_cursos (NOME_CURSO,TEMPO_CURSO,PRECO,PROFESSOR,CATEGORIAS_ID)
VALUE("MARKETING",5,4200.00,"SAMANTA MORALES",3);
INSERT INTO tb_cursos (NOME_CURSO,TEMPO_CURSO,PRECO,PROFESSOR,CATEGORIAS_ID)
VALUE("MAQUIAGEM",1,1200.00,"RUTH GODOY",5);
INSERT INTO tb_cursos (NOME_CURSO,TEMPO_CURSO,PRECO,PROFESSOR,CATEGORIAS_ID)
VALUE("INFORMATICA",2,1200.00,"MARCELO FERRAZ",1);
INSERT INTO tb_cursos (NOME_CURSO,TEMPO_CURSO,PRECO,PROFESSOR,CATEGORIAS_ID)
VALUE("INFORMATICA",2,1200.00,"RUBIA BARBOSA",4);

SELECT * FROM tb_cursos;
SELECT * FROM tb_cursos WHERE PRECO>500.00;
SELECT * FROM tb_cursos WHERE PRECO>600.00 and PRECO<1000.00;
SELECT * FROM tb_cursos WHERE NOME_CURSO LIKE '%J%';
select * from tb_cursos inner join tb_categorias on  tb_categorias.id = tb_cursos.CATEGORIAS_ID;
select * from tb_cursos inner join tb_categorias on  tb_categorias.id = tb_cursos.CATEGORIAS_ID
WHERE PERIODO="NOITE";
